name: Generate GitHub Snake

on:
  push:
    branches:
      - main  # 你可以根据需求更改为你的默认分支
  pull_request:
    branches:
      - main  # 触发PR时也生成

jobs:
  generate-snake:
    runs-on: ubuntu-latest  # 你可以选择其他运行环境，如 Windows 或 MacOS
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Generate GitHub Snake
      uses: Platane/snk@v3
      with:
        github_user_name: SnowLegend-star  # 使用仓库拥有者的 GitHub 用户名
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
